### ISSUE TITLE
Basic Features TODO

### ISSUE THREAD

**Issue by SFantasy** [SFantasy/WeiboReactNative#2]
- [x] 登录用户 Profile 展示 （接口：http://open.weibo.com/wiki/2/users/show）
- [x] 展示最近的微博 (接口：http://open.weibo.com/wiki/2/statuses/user_timeline)
- [x] 用户的 home_timline (接口：http://open.weibo.com/wiki/2/statuses/home_timeline)
- [x] 发表微博 （http://open.weibo.com/wiki/2/statuses/update）
- [ ] 微博的评论
- [ ] 转发
- [ ] 点赞
- [ ] URL 用 `LinkingIOS` 打开
- [ ] 用户列表（Follower 和 Following）
- [x] 消息列表

**Comment by SFantasy** [comment]
TODO
- [ ] URL 用 `LinkingIOS` 打开
- [ ] 展示最近的微博
